-- MySQL Script generated by MySQL Workbench
-- Wed Jul 22 22:17:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Reddit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Reddit` ;

-- -----------------------------------------------------
-- Schema Reddit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Reddit` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Reddit` ;

-- -----------------------------------------------------
-- Table `Reddit`.`Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reddit`.`Log` ;

CREATE TABLE IF NOT EXISTS `Reddit`.`Log` (
  `utc` INT NOT NULL,
  `username` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `action` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`utc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Reddit`.`Mafia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reddit`.`Mafia` ;

CREATE TABLE IF NOT EXISTS `Reddit`.`Mafia` (
  `utc` INT NOT NULL,
  `username` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `team` INT NOT NULL DEFAULT '-1',
  `tier` INT NOT NULL DEFAULT '0',
  `loc` VARCHAR(255) NULL DEFAULT NULL,
  `alive` INT NOT NULL DEFAULT '1',
  `diedOnCycle` INT NULL DEFAULT NULL,
  `burn` INT NOT NULL DEFAULT '1',
  `revive` INT NOT NULL DEFAULT '1',
  `request` INT NOT NULL DEFAULT '3',
  `comment` INT NOT NULL DEFAULT '0',
  `inactive` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`utc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Reddit`.`TeamInvite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reddit`.`TeamInvite` ;

CREATE TABLE IF NOT EXISTS `Reddit`.`TeamInvite` (
  `username` VARCHAR(20) NOT NULL,
  `target` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Reddit`.`VoteCall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reddit`.`VoteCall` ;

CREATE TABLE IF NOT EXISTS `Reddit`.`VoteCall` (
  `username` VARCHAR(20) NOT NULL,
  `vote` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

USE `Reddit` ;

-- -----------------------------------------------------
-- procedure role_cnt
-- -----------------------------------------------------

USE `Reddit`;
DROP procedure IF EXISTS `Reddit`.`role_cnt`;

DELIMITER $$
USE `Reddit`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `role_cnt`()
BEGIN
SELECT team,COUNT(*) as cnt
FROM Mafia
GROUP BY team
ORDER BY team DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure role_cnt_alive
-- -----------------------------------------------------

USE `Reddit`;
DROP procedure IF EXISTS `Reddit`.`role_cnt_alive`;

DELIMITER $$
USE `Reddit`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `role_cnt_alive`()
BEGIN
SELECT team,COUNT(*) as cnt
FROM Mafia
WHERE alive=1
GROUP BY team
ORDER BY team DESC;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
